package com.qaqzz.socket.database;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageDaoConfig;
    private final DaoConfig chatRecordDaoConfig;

    private final MessageDao messageDao;
    private final ChatRecordDao chatRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        chatRecordDaoConfig = daoConfigMap.get(ChatRecordDao.class).clone();
        chatRecordDaoConfig.initIdentityScope(type);

        messageDao = new MessageDao(messageDaoConfig, this);
        chatRecordDao = new ChatRecordDao(chatRecordDaoConfig, this);

        registerDao(Message.class, messageDao);
        registerDao(ChatRecord.class, chatRecordDao);
    }
    
    public void clear() {
        messageDaoConfig.clearIdentityScope();
        chatRecordDaoConfig.clearIdentityScope();
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public ChatRecordDao getChatRecordDao() {
        return chatRecordDao;
    }

}
