package com.qaqzz.socket.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.qaqzz.socket.database.ChatRecord;
import com.qaqzz.socket.database.Message;

import com.qaqzz.socket.database.ChatRecordDao;
import com.qaqzz.socket.database.MessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatRecordDaoConfig;
    private final DaoConfig messageDaoConfig;

    private final ChatRecordDao chatRecordDao;
    private final MessageDao messageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatRecordDaoConfig = daoConfigMap.get(ChatRecordDao.class).clone();
        chatRecordDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        chatRecordDao = new ChatRecordDao(chatRecordDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);

        registerDao(ChatRecord.class, chatRecordDao);
        registerDao(Message.class, messageDao);
    }
    
    public void clear() {
        chatRecordDaoConfig.clearIdentityScope();
        messageDaoConfig.clearIdentityScope();
    }

    public ChatRecordDao getChatRecordDao() {
        return chatRecordDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

}
